version: '1'
services:
    falco:
        image: sysdig/falco
        volumes:
           - ./var/run/docker.sock:/host/var/run/docker.sock \
           - ./dev:/host/dev \
           - ./proc:/host/proc:ro \
           - ./boot:/host/boot:ro \
           - ./lib/modules:/host/lib/modules:ro \
           - ./usr:/host/usr:ro \
           - ./etc/falco/falco_rules.yaml:/etc/falco/falco_rules.yaml
           - ./etc/falco/falco.yaml:/etc/falco/falco.yaml

        links:
            -fluentd
        logging:
              driver: "fluentd"
        options:
            fluentd-address: localhost:8080
            tag: falco_events


    elasticsearch:
        image: elasticsearch
        environment:
              discovery.type: single-node
        ports:
              - 9200:9200
              - 9300:9300

    fluentd:
        build: ./fluentd
        volumes:
              - ./fluentd/conf:/fluentd/etc
              - ./logs:/logs
        links:
        - "elasticsearch"
        ports:
              - 8080:8080



    kibana:
        image: kibana
        environment:
             ELASTICSEARCH_URL: http://elasticsearch:9200
        links:
            - "elasticsearch"
        ports:
              - 5601:5601
