version: '1'
services:


    elasticsearch:
        image: elasticsearch
        environment:
              discovery.type: single-node
        ports:
              - 9200:9200
              - 9300:9300

    fluentd:
        build: ./fluentd
        volumes:
              - ./fluentd/conf:/fluentd/etc
              - ./logs:/logs
        links:
        - "elasticsearch"
        ports:
              - 8080:8080



    kibana:
        image: kibana
        environment:
             ELASTICSEARCH_URL: http://elasticsearch:9200
        links:
            - "elasticsearch"
        ports:
              - 5601:5601
